cargo-features = [ "per-package-target" ]

[package]
name = "app"
version = "0.1.0"
edition = "2021"
default-target = "wasm32-wasi"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
serde_json = "*"
common = { path = "../common" }
