[package]
name = "host-wasmedge"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", tag = "v0.2.0" }
wasmedge-sdk = "0.5.0"
anyhow = "*"
